kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: local
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  # Minio (Object Storage)
  - containerPort: 9000
    hostPort: 9000
    protocol: TCP
  - containerPort: 9001
    hostPort: 9001
    protocol: TCP
  # Nessie (Iceberg Catalog)
  - containerPort: 19120
    hostPort: 19120
    protocol: TCP
  # Trino (Distributed SQL Query Engine)
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
# Worker nodes
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
- role: worker
